name: Loife Update

on:
  schedule:
    - cron:  '0 8 * * 1' # every Monday at 8am
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Dependencies
        uses: actions/setup-node@v3
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      - run: npm ci

      - name: Update
        uses: mujo-code/puppeteer-headful@v2
        env:
          CI: 'true'
        with:
          args: npm start

      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
